/* tslint:disable */
/* eslint-disable */
/**
 * Unofficial Crossway ESV API
 * This is an **unofficial** API spec for the ESV Bible from Crossway.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * The response object for textual (e.g. text or HTML) passages.
 * @export
 * @interface PassageTextualResponse
 */
export interface PassageTextualResponse {
    /**
     * The passage query.
     * @type {string}
     * @memberof PassageTextualResponse
     */
    'query'?: string;
    /**
     * The canonical passage.
     * @type {string}
     * @memberof PassageTextualResponse
     */
    'canonical'?: string;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof PassageTextualResponse
     */
    'parsed'?: Array<Array<number>>;
    /**
     * 
     * @type {Array<PassageTextualResponsePassageMetaInner>}
     * @memberof PassageTextualResponse
     */
    'passage_meta'?: Array<PassageTextualResponsePassageMetaInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PassageTextualResponse
     */
    'passages'?: Array<string>;
}
/**
 * 
 * @export
 * @interface PassageTextualResponsePassageMetaInner
 */
export interface PassageTextualResponsePassageMetaInner {
    /**
     * The canonical passage.
     * @type {string}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'canonical'?: string;
    /**
     * The chapter start.
     * @type {Array<number>}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'chapter_start'?: Array<number>;
    /**
     * The chapter end.
     * @type {Array<number>}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'chapter_end'?: Array<number>;
    /**
     * The previous verse.
     * @type {number}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'prev_verse'?: number;
    /**
     * The next verse.
     * @type {number}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'next_verse'?: number;
    /**
     * The previous chapter.
     * @type {Array<number>}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'prev_chapter'?: Array<number>;
    /**
     * The next chapter.
     * @type {Array<number>}
     * @memberof PassageTextualResponsePassageMetaInner
     */
    'next_chapter'?: Array<number>;
}
/**
 * 
 * @export
 * @interface V3PassageSearchGet200Response
 */
export interface V3PassageSearchGet200Response {
    /**
     * The current page.
     * @type {number}
     * @memberof V3PassageSearchGet200Response
     */
    'page'?: number;
    /**
     * The total number of results.
     * @type {number}
     * @memberof V3PassageSearchGet200Response
     */
    'total_results'?: number;
    /**
     * 
     * @type {Array<V3PassageSearchGet200ResponseResultsInner>}
     * @memberof V3PassageSearchGet200Response
     */
    'results'?: Array<V3PassageSearchGet200ResponseResultsInner>;
    /**
     * The total number of pages.
     * @type {number}
     * @memberof V3PassageSearchGet200Response
     */
    'total_pages'?: number;
}
/**
 * 
 * @export
 * @interface V3PassageSearchGet200ResponseResultsInner
 */
export interface V3PassageSearchGet200ResponseResultsInner {
    /**
     * The reference.
     * @type {string}
     * @memberof V3PassageSearchGet200ResponseResultsInner
     */
    'reference'?: string;
    /**
     * The content.
     * @type {string}
     * @memberof V3PassageSearchGet200ResponseResultsInner
     */
    'content'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Passage Audio
         * @param {string} q This is the requested passage. We try our best to parse a meaningful passage reference from this value.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageAudioGet: async (q: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('v3PassageAudioGet', 'q', q)
            const localVarPath = `/v3/passage/audio/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication API_Key required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Passage HTML
         * @param {string} q This is the requested passage. We try our best to parse a meaningful passage reference from this value.
         * @param {boolean} [includePassageReferences] Include the passage reference before the text.
         * @param {boolean} [includeVerseNumbers] Include verse numbers.
         * @param {boolean} [includeFirstVerseNumbers] Include the verse number for the first verse of a chapter.
         * @param {boolean} [includeFootnotes] Include callouts to footnotes in the text.
         * @param {boolean} [includeFootnoteBody] Include footnote bodies below the text. Only works if include-footnotes is also true.
         * @param {boolean} [includeHeadings] Include section headings. For example, the section heading of Matthew 5 is \&quot;The Sermon on the Mount\&quot;.
         * @param {boolean} [includeShortCopyright] Include \&quot;(ESV)\&quot; at the end of the text. Mutually exclusive with include-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includeCopyright] Include a copyright notice at the end of the text. Mutually exclusive with include-short-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includeCssLink] Include a link tag that provides CSS for the returned text.
         * @param {boolean} [inlineStyles] Include inline CSS for the returned text.
         * @param {boolean} [wrappingDiv] Wrap the text in a div tag with feature classes applied.
         * @param {string} [divClasses] Add extra CSS classes to the wrapping div generated by the option above.
         * @param {string} [paragraphTag] Customize the HTML tag used for paragraph elements.
         * @param {boolean} [includeBookTitles] Include an h2 containing a book name if the first verse of a book is in the requested text.
         * @param {boolean} [includeVerseAnchors] Add an anchor tag at every verse and heading boundary containing embedded verse data.
         * @param {boolean} [includeChapterNumbers] Include a chapter number if the first verse in a chapter is in the requested text.
         * @param {boolean} [includeCrossrefs] Include cross-reference call-outs in the text.
         * @param {boolean} [includeSubheadings] Include subheadings. Subheadings are the titles of psalms (e.g., Psalm 73\&#39;s \&#39;A Maskil of Asaph\&#39;), the acrostic divisions in Psalm 119, the speakers in Song of Solomon, and the textual notes that appear in John 7 and Mark 16.
         * @param {boolean} [includeSurroundingChapters] Show links above the text to the previous, current (if not showing the whole chapter) and next chapters in the Bible. You can modify the link by changing the link-url parameter.
         * @param {V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum} [includeSurroundingChaptersBelow] Same as the include-surrounding-chapters parameter above, but the links are rendered below the text. This value may also be the string smart, in which case the links will be shown based on the include-surrounding-chapters parameter.
         * @param {string} [linkUrl] Where embedded links to other passages should point. Applies only when include-surrounding-chapters is set to true.
         * @param {string} [crossrefUrl] Where embedded cross reference links should point. Only applies if include-crossrefs is true.
         * @param {string} [prefaceUrl] Where embedded links to the preface should point. Only applies if include-footnotes is true.
         * @param {boolean} [includeAudioLink] Include a link to the audio version of the requested passage. The link appears in a small tag in the passage\&#39;s identifying h2 tag.
         * @param {V3PassageHtmlGetAttachAudioLinkToEnum} [attachAudioLinkTo] Which feature to attach the audio link to. Must be either passage or heading.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageHtmlGet: async (q: string, includePassageReferences?: boolean, includeVerseNumbers?: boolean, includeFirstVerseNumbers?: boolean, includeFootnotes?: boolean, includeFootnoteBody?: boolean, includeHeadings?: boolean, includeShortCopyright?: boolean, includeCopyright?: boolean, includeCssLink?: boolean, inlineStyles?: boolean, wrappingDiv?: boolean, divClasses?: string, paragraphTag?: string, includeBookTitles?: boolean, includeVerseAnchors?: boolean, includeChapterNumbers?: boolean, includeCrossrefs?: boolean, includeSubheadings?: boolean, includeSurroundingChapters?: boolean, includeSurroundingChaptersBelow?: V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum, linkUrl?: string, crossrefUrl?: string, prefaceUrl?: string, includeAudioLink?: boolean, attachAudioLinkTo?: V3PassageHtmlGetAttachAudioLinkToEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('v3PassageHtmlGet', 'q', q)
            const localVarPath = `/v3/passage/html/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication API_Key required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (includePassageReferences !== undefined) {
                localVarQueryParameter['include-passage-references'] = includePassageReferences;
            }

            if (includeVerseNumbers !== undefined) {
                localVarQueryParameter['include-verse-numbers'] = includeVerseNumbers;
            }

            if (includeFirstVerseNumbers !== undefined) {
                localVarQueryParameter['include-first-verse-numbers'] = includeFirstVerseNumbers;
            }

            if (includeFootnotes !== undefined) {
                localVarQueryParameter['include-footnotes'] = includeFootnotes;
            }

            if (includeFootnoteBody !== undefined) {
                localVarQueryParameter['include-footnote-body'] = includeFootnoteBody;
            }

            if (includeHeadings !== undefined) {
                localVarQueryParameter['include-headings'] = includeHeadings;
            }

            if (includeShortCopyright !== undefined) {
                localVarQueryParameter['include-short-copyright'] = includeShortCopyright;
            }

            if (includeCopyright !== undefined) {
                localVarQueryParameter['include-copyright'] = includeCopyright;
            }

            if (includeCssLink !== undefined) {
                localVarQueryParameter['include-css-link'] = includeCssLink;
            }

            if (inlineStyles !== undefined) {
                localVarQueryParameter['inline-styles'] = inlineStyles;
            }

            if (wrappingDiv !== undefined) {
                localVarQueryParameter['wrapping-div'] = wrappingDiv;
            }

            if (divClasses !== undefined) {
                localVarQueryParameter['div-classes'] = divClasses;
            }

            if (paragraphTag !== undefined) {
                localVarQueryParameter['paragraph-tag'] = paragraphTag;
            }

            if (includeBookTitles !== undefined) {
                localVarQueryParameter['include-book-titles'] = includeBookTitles;
            }

            if (includeVerseAnchors !== undefined) {
                localVarQueryParameter['include-verse-anchors'] = includeVerseAnchors;
            }

            if (includeChapterNumbers !== undefined) {
                localVarQueryParameter['include-chapter-numbers'] = includeChapterNumbers;
            }

            if (includeCrossrefs !== undefined) {
                localVarQueryParameter['include-crossrefs'] = includeCrossrefs;
            }

            if (includeSubheadings !== undefined) {
                localVarQueryParameter['include-subheadings'] = includeSubheadings;
            }

            if (includeSurroundingChapters !== undefined) {
                localVarQueryParameter['include-surrounding-chapters'] = includeSurroundingChapters;
            }

            if (includeSurroundingChaptersBelow !== undefined) {
                localVarQueryParameter['include-surrounding-chapters-below'] = includeSurroundingChaptersBelow;
            }

            if (linkUrl !== undefined) {
                localVarQueryParameter['link-url'] = linkUrl;
            }

            if (crossrefUrl !== undefined) {
                localVarQueryParameter['crossref-url'] = crossrefUrl;
            }

            if (prefaceUrl !== undefined) {
                localVarQueryParameter['preface-url'] = prefaceUrl;
            }

            if (includeAudioLink !== undefined) {
                localVarQueryParameter['include-audio-link'] = includeAudioLink;
            }

            if (attachAudioLinkTo !== undefined) {
                localVarQueryParameter['attach-audio-link-to'] = attachAudioLinkTo;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search for Passages
         * @param {string} q The search query. If you want results for an exact phrase, wrap your query in double quotes. For instance, the query in love returns many more results than the query \&quot;in love\&quot; because the latter only returns matches for the exact phrase.
         * @param {number} [pageSize] The number of results per page.
         * @param {number} [page] Which page of results you want. This parameter works in conjunction with the page-size parameter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageSearchGet: async (q: string, pageSize?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('v3PassageSearchGet', 'q', q)
            const localVarPath = `/v3/passage/search/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication API_Key required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page-size'] = pageSize;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Passage Text
         * @param {string} q This is the requested passage. We try our best to parse a meaningful passage reference from this value.
         * @param {boolean} [includePassageReferences] Include the passage reference before the text.
         * @param {boolean} [includeVerseNumbers] Include verse numbers.
         * @param {boolean} [includeFirstVerseNumbers] Include the verse number for the first verse of a chapter.
         * @param {boolean} [includeFootnotes] Include callouts to footnotes in the text.
         * @param {boolean} [includeFootnoteBody] Include footnote bodies below the text. Only works if include-footnotes is also true.
         * @param {boolean} [includeHeadings] Include section headings. For example, the section heading of Matthew 5 is \&quot;The Sermon on the Mount\&quot;.
         * @param {boolean} [includeShortCopyright] Include \&quot;(ESV)\&quot; at the end of the text. Mutually exclusive with include-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includeCopyright] Include a copyright notice at the end of the text. Mutually exclusive with include-short-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includePassageHorizontalLines] Include a line of equal signs (&#x3D;&#x3D;&#x3D;&#x3D;) above the beginning of each passage.
         * @param {boolean} [includeHeadingHorizontalLines] Include a visual line of underscores (____) above each section heading.
         * @param {number} [horiztonalLineLength] Controls the length of the line for include-passage-horizontal-lines and include-heading-horizontal-lines.
         * @param {boolean} [includeSelahs] Include \&quot;Selah\&quot; in certain Psalms.
         * @param {V3PassageTextGetIndentUsingEnum} [indentUsing] Controls indentation.
         * @param {number} [indentParagraphs] Controls how many indentation characters start a paragraph.
         * @param {boolean} [indentPoetry] Controls indentation of poetry lines.
         * @param {number} [indentPoetryLines] Controls how many indentation characters are used per indentation level for poetry lines.
         * @param {number} [indentDeclares] Controls how many indentation characters are used for \&quot;Declares the LORD\&quot; in some of the prophets.\&quot;
         * @param {number} [indentPsalmDoxology] Controls how many indentation characters are used for Psalm doxologies.
         * @param {number} [lineLength] Controls how long a line can be before it is wrapped. Use 0 for unlimited line lengths.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageTextGet: async (q: string, includePassageReferences?: boolean, includeVerseNumbers?: boolean, includeFirstVerseNumbers?: boolean, includeFootnotes?: boolean, includeFootnoteBody?: boolean, includeHeadings?: boolean, includeShortCopyright?: boolean, includeCopyright?: boolean, includePassageHorizontalLines?: boolean, includeHeadingHorizontalLines?: boolean, horiztonalLineLength?: number, includeSelahs?: boolean, indentUsing?: V3PassageTextGetIndentUsingEnum, indentParagraphs?: number, indentPoetry?: boolean, indentPoetryLines?: number, indentDeclares?: number, indentPsalmDoxology?: number, lineLength?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('v3PassageTextGet', 'q', q)
            const localVarPath = `/v3/passage/text/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication API_Key required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (includePassageReferences !== undefined) {
                localVarQueryParameter['include-passage-references'] = includePassageReferences;
            }

            if (includeVerseNumbers !== undefined) {
                localVarQueryParameter['include-verse-numbers'] = includeVerseNumbers;
            }

            if (includeFirstVerseNumbers !== undefined) {
                localVarQueryParameter['include-first-verse-numbers'] = includeFirstVerseNumbers;
            }

            if (includeFootnotes !== undefined) {
                localVarQueryParameter['include-footnotes'] = includeFootnotes;
            }

            if (includeFootnoteBody !== undefined) {
                localVarQueryParameter['include-footnote-body'] = includeFootnoteBody;
            }

            if (includeHeadings !== undefined) {
                localVarQueryParameter['include-headings'] = includeHeadings;
            }

            if (includeShortCopyright !== undefined) {
                localVarQueryParameter['include-short-copyright'] = includeShortCopyright;
            }

            if (includeCopyright !== undefined) {
                localVarQueryParameter['include-copyright'] = includeCopyright;
            }

            if (includePassageHorizontalLines !== undefined) {
                localVarQueryParameter['include-passage-horizontal-lines'] = includePassageHorizontalLines;
            }

            if (includeHeadingHorizontalLines !== undefined) {
                localVarQueryParameter['include-heading-horizontal-lines'] = includeHeadingHorizontalLines;
            }

            if (horiztonalLineLength !== undefined) {
                localVarQueryParameter['horiztonal-line-length'] = horiztonalLineLength;
            }

            if (includeSelahs !== undefined) {
                localVarQueryParameter['include-selahs'] = includeSelahs;
            }

            if (indentUsing !== undefined) {
                localVarQueryParameter['indent-using'] = indentUsing;
            }

            if (indentParagraphs !== undefined) {
                localVarQueryParameter['indent-paragraphs'] = indentParagraphs;
            }

            if (indentPoetry !== undefined) {
                localVarQueryParameter['indent-poetry'] = indentPoetry;
            }

            if (indentPoetryLines !== undefined) {
                localVarQueryParameter['indent-poetry-lines'] = indentPoetryLines;
            }

            if (indentDeclares !== undefined) {
                localVarQueryParameter['indent-declares'] = indentDeclares;
            }

            if (indentPsalmDoxology !== undefined) {
                localVarQueryParameter['indent-psalm-doxology'] = indentPsalmDoxology;
            }

            if (lineLength !== undefined) {
                localVarQueryParameter['line-length'] = lineLength;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Passage Audio
         * @param {string} q This is the requested passage. We try our best to parse a meaningful passage reference from this value.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3PassageAudioGet(q: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3PassageAudioGet(q, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v3PassageAudioGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Passage HTML
         * @param {string} q This is the requested passage. We try our best to parse a meaningful passage reference from this value.
         * @param {boolean} [includePassageReferences] Include the passage reference before the text.
         * @param {boolean} [includeVerseNumbers] Include verse numbers.
         * @param {boolean} [includeFirstVerseNumbers] Include the verse number for the first verse of a chapter.
         * @param {boolean} [includeFootnotes] Include callouts to footnotes in the text.
         * @param {boolean} [includeFootnoteBody] Include footnote bodies below the text. Only works if include-footnotes is also true.
         * @param {boolean} [includeHeadings] Include section headings. For example, the section heading of Matthew 5 is \&quot;The Sermon on the Mount\&quot;.
         * @param {boolean} [includeShortCopyright] Include \&quot;(ESV)\&quot; at the end of the text. Mutually exclusive with include-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includeCopyright] Include a copyright notice at the end of the text. Mutually exclusive with include-short-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includeCssLink] Include a link tag that provides CSS for the returned text.
         * @param {boolean} [inlineStyles] Include inline CSS for the returned text.
         * @param {boolean} [wrappingDiv] Wrap the text in a div tag with feature classes applied.
         * @param {string} [divClasses] Add extra CSS classes to the wrapping div generated by the option above.
         * @param {string} [paragraphTag] Customize the HTML tag used for paragraph elements.
         * @param {boolean} [includeBookTitles] Include an h2 containing a book name if the first verse of a book is in the requested text.
         * @param {boolean} [includeVerseAnchors] Add an anchor tag at every verse and heading boundary containing embedded verse data.
         * @param {boolean} [includeChapterNumbers] Include a chapter number if the first verse in a chapter is in the requested text.
         * @param {boolean} [includeCrossrefs] Include cross-reference call-outs in the text.
         * @param {boolean} [includeSubheadings] Include subheadings. Subheadings are the titles of psalms (e.g., Psalm 73\&#39;s \&#39;A Maskil of Asaph\&#39;), the acrostic divisions in Psalm 119, the speakers in Song of Solomon, and the textual notes that appear in John 7 and Mark 16.
         * @param {boolean} [includeSurroundingChapters] Show links above the text to the previous, current (if not showing the whole chapter) and next chapters in the Bible. You can modify the link by changing the link-url parameter.
         * @param {V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum} [includeSurroundingChaptersBelow] Same as the include-surrounding-chapters parameter above, but the links are rendered below the text. This value may also be the string smart, in which case the links will be shown based on the include-surrounding-chapters parameter.
         * @param {string} [linkUrl] Where embedded links to other passages should point. Applies only when include-surrounding-chapters is set to true.
         * @param {string} [crossrefUrl] Where embedded cross reference links should point. Only applies if include-crossrefs is true.
         * @param {string} [prefaceUrl] Where embedded links to the preface should point. Only applies if include-footnotes is true.
         * @param {boolean} [includeAudioLink] Include a link to the audio version of the requested passage. The link appears in a small tag in the passage\&#39;s identifying h2 tag.
         * @param {V3PassageHtmlGetAttachAudioLinkToEnum} [attachAudioLinkTo] Which feature to attach the audio link to. Must be either passage or heading.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3PassageHtmlGet(q: string, includePassageReferences?: boolean, includeVerseNumbers?: boolean, includeFirstVerseNumbers?: boolean, includeFootnotes?: boolean, includeFootnoteBody?: boolean, includeHeadings?: boolean, includeShortCopyright?: boolean, includeCopyright?: boolean, includeCssLink?: boolean, inlineStyles?: boolean, wrappingDiv?: boolean, divClasses?: string, paragraphTag?: string, includeBookTitles?: boolean, includeVerseAnchors?: boolean, includeChapterNumbers?: boolean, includeCrossrefs?: boolean, includeSubheadings?: boolean, includeSurroundingChapters?: boolean, includeSurroundingChaptersBelow?: V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum, linkUrl?: string, crossrefUrl?: string, prefaceUrl?: string, includeAudioLink?: boolean, attachAudioLinkTo?: V3PassageHtmlGetAttachAudioLinkToEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PassageTextualResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3PassageHtmlGet(q, includePassageReferences, includeVerseNumbers, includeFirstVerseNumbers, includeFootnotes, includeFootnoteBody, includeHeadings, includeShortCopyright, includeCopyright, includeCssLink, inlineStyles, wrappingDiv, divClasses, paragraphTag, includeBookTitles, includeVerseAnchors, includeChapterNumbers, includeCrossrefs, includeSubheadings, includeSurroundingChapters, includeSurroundingChaptersBelow, linkUrl, crossrefUrl, prefaceUrl, includeAudioLink, attachAudioLinkTo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v3PassageHtmlGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search for Passages
         * @param {string} q The search query. If you want results for an exact phrase, wrap your query in double quotes. For instance, the query in love returns many more results than the query \&quot;in love\&quot; because the latter only returns matches for the exact phrase.
         * @param {number} [pageSize] The number of results per page.
         * @param {number} [page] Which page of results you want. This parameter works in conjunction with the page-size parameter.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3PassageSearchGet(q: string, pageSize?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V3PassageSearchGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3PassageSearchGet(q, pageSize, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v3PassageSearchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Passage Text
         * @param {string} q This is the requested passage. We try our best to parse a meaningful passage reference from this value.
         * @param {boolean} [includePassageReferences] Include the passage reference before the text.
         * @param {boolean} [includeVerseNumbers] Include verse numbers.
         * @param {boolean} [includeFirstVerseNumbers] Include the verse number for the first verse of a chapter.
         * @param {boolean} [includeFootnotes] Include callouts to footnotes in the text.
         * @param {boolean} [includeFootnoteBody] Include footnote bodies below the text. Only works if include-footnotes is also true.
         * @param {boolean} [includeHeadings] Include section headings. For example, the section heading of Matthew 5 is \&quot;The Sermon on the Mount\&quot;.
         * @param {boolean} [includeShortCopyright] Include \&quot;(ESV)\&quot; at the end of the text. Mutually exclusive with include-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includeCopyright] Include a copyright notice at the end of the text. Mutually exclusive with include-short-copyright. This fulfills your copyright display requirements.
         * @param {boolean} [includePassageHorizontalLines] Include a line of equal signs (&#x3D;&#x3D;&#x3D;&#x3D;) above the beginning of each passage.
         * @param {boolean} [includeHeadingHorizontalLines] Include a visual line of underscores (____) above each section heading.
         * @param {number} [horiztonalLineLength] Controls the length of the line for include-passage-horizontal-lines and include-heading-horizontal-lines.
         * @param {boolean} [includeSelahs] Include \&quot;Selah\&quot; in certain Psalms.
         * @param {V3PassageTextGetIndentUsingEnum} [indentUsing] Controls indentation.
         * @param {number} [indentParagraphs] Controls how many indentation characters start a paragraph.
         * @param {boolean} [indentPoetry] Controls indentation of poetry lines.
         * @param {number} [indentPoetryLines] Controls how many indentation characters are used per indentation level for poetry lines.
         * @param {number} [indentDeclares] Controls how many indentation characters are used for \&quot;Declares the LORD\&quot; in some of the prophets.\&quot;
         * @param {number} [indentPsalmDoxology] Controls how many indentation characters are used for Psalm doxologies.
         * @param {number} [lineLength] Controls how long a line can be before it is wrapped. Use 0 for unlimited line lengths.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v3PassageTextGet(q: string, includePassageReferences?: boolean, includeVerseNumbers?: boolean, includeFirstVerseNumbers?: boolean, includeFootnotes?: boolean, includeFootnoteBody?: boolean, includeHeadings?: boolean, includeShortCopyright?: boolean, includeCopyright?: boolean, includePassageHorizontalLines?: boolean, includeHeadingHorizontalLines?: boolean, horiztonalLineLength?: number, includeSelahs?: boolean, indentUsing?: V3PassageTextGetIndentUsingEnum, indentParagraphs?: number, indentPoetry?: boolean, indentPoetryLines?: number, indentDeclares?: number, indentPsalmDoxology?: number, lineLength?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PassageTextualResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v3PassageTextGet(q, includePassageReferences, includeVerseNumbers, includeFirstVerseNumbers, includeFootnotes, includeFootnoteBody, includeHeadings, includeShortCopyright, includeCopyright, includePassageHorizontalLines, includeHeadingHorizontalLines, horiztonalLineLength, includeSelahs, indentUsing, indentParagraphs, indentPoetry, indentPoetryLines, indentDeclares, indentPsalmDoxology, lineLength, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.v3PassageTextGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Passage Audio
         * @param {DefaultApiV3PassageAudioGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageAudioGet(requestParameters: DefaultApiV3PassageAudioGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.v3PassageAudioGet(requestParameters.q, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Passage HTML
         * @param {DefaultApiV3PassageHtmlGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageHtmlGet(requestParameters: DefaultApiV3PassageHtmlGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PassageTextualResponse> {
            return localVarFp.v3PassageHtmlGet(requestParameters.q, requestParameters.includePassageReferences, requestParameters.includeVerseNumbers, requestParameters.includeFirstVerseNumbers, requestParameters.includeFootnotes, requestParameters.includeFootnoteBody, requestParameters.includeHeadings, requestParameters.includeShortCopyright, requestParameters.includeCopyright, requestParameters.includeCssLink, requestParameters.inlineStyles, requestParameters.wrappingDiv, requestParameters.divClasses, requestParameters.paragraphTag, requestParameters.includeBookTitles, requestParameters.includeVerseAnchors, requestParameters.includeChapterNumbers, requestParameters.includeCrossrefs, requestParameters.includeSubheadings, requestParameters.includeSurroundingChapters, requestParameters.includeSurroundingChaptersBelow, requestParameters.linkUrl, requestParameters.crossrefUrl, requestParameters.prefaceUrl, requestParameters.includeAudioLink, requestParameters.attachAudioLinkTo, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search for Passages
         * @param {DefaultApiV3PassageSearchGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageSearchGet(requestParameters: DefaultApiV3PassageSearchGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<V3PassageSearchGet200Response> {
            return localVarFp.v3PassageSearchGet(requestParameters.q, requestParameters.pageSize, requestParameters.page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Passage Text
         * @param {DefaultApiV3PassageTextGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v3PassageTextGet(requestParameters: DefaultApiV3PassageTextGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PassageTextualResponse> {
            return localVarFp.v3PassageTextGet(requestParameters.q, requestParameters.includePassageReferences, requestParameters.includeVerseNumbers, requestParameters.includeFirstVerseNumbers, requestParameters.includeFootnotes, requestParameters.includeFootnoteBody, requestParameters.includeHeadings, requestParameters.includeShortCopyright, requestParameters.includeCopyright, requestParameters.includePassageHorizontalLines, requestParameters.includeHeadingHorizontalLines, requestParameters.horiztonalLineLength, requestParameters.includeSelahs, requestParameters.indentUsing, requestParameters.indentParagraphs, requestParameters.indentPoetry, requestParameters.indentPoetryLines, requestParameters.indentDeclares, requestParameters.indentPsalmDoxology, requestParameters.lineLength, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for v3PassageAudioGet operation in DefaultApi.
 * @export
 * @interface DefaultApiV3PassageAudioGetRequest
 */
export interface DefaultApiV3PassageAudioGetRequest {
    /**
     * This is the requested passage. We try our best to parse a meaningful passage reference from this value.
     * @type {string}
     * @memberof DefaultApiV3PassageAudioGet
     */
    readonly q: string
}

/**
 * Request parameters for v3PassageHtmlGet operation in DefaultApi.
 * @export
 * @interface DefaultApiV3PassageHtmlGetRequest
 */
export interface DefaultApiV3PassageHtmlGetRequest {
    /**
     * This is the requested passage. We try our best to parse a meaningful passage reference from this value.
     * @type {string}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly q: string

    /**
     * Include the passage reference before the text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includePassageReferences?: boolean

    /**
     * Include verse numbers.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeVerseNumbers?: boolean

    /**
     * Include the verse number for the first verse of a chapter.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeFirstVerseNumbers?: boolean

    /**
     * Include callouts to footnotes in the text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeFootnotes?: boolean

    /**
     * Include footnote bodies below the text. Only works if include-footnotes is also true.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeFootnoteBody?: boolean

    /**
     * Include section headings. For example, the section heading of Matthew 5 is \&quot;The Sermon on the Mount\&quot;.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeHeadings?: boolean

    /**
     * Include \&quot;(ESV)\&quot; at the end of the text. Mutually exclusive with include-copyright. This fulfills your copyright display requirements.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeShortCopyright?: boolean

    /**
     * Include a copyright notice at the end of the text. Mutually exclusive with include-short-copyright. This fulfills your copyright display requirements.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeCopyright?: boolean

    /**
     * Include a link tag that provides CSS for the returned text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeCssLink?: boolean

    /**
     * Include inline CSS for the returned text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly inlineStyles?: boolean

    /**
     * Wrap the text in a div tag with feature classes applied.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly wrappingDiv?: boolean

    /**
     * Add extra CSS classes to the wrapping div generated by the option above.
     * @type {string}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly divClasses?: string

    /**
     * Customize the HTML tag used for paragraph elements.
     * @type {string}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly paragraphTag?: string

    /**
     * Include an h2 containing a book name if the first verse of a book is in the requested text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeBookTitles?: boolean

    /**
     * Add an anchor tag at every verse and heading boundary containing embedded verse data.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeVerseAnchors?: boolean

    /**
     * Include a chapter number if the first verse in a chapter is in the requested text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeChapterNumbers?: boolean

    /**
     * Include cross-reference call-outs in the text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeCrossrefs?: boolean

    /**
     * Include subheadings. Subheadings are the titles of psalms (e.g., Psalm 73\&#39;s \&#39;A Maskil of Asaph\&#39;), the acrostic divisions in Psalm 119, the speakers in Song of Solomon, and the textual notes that appear in John 7 and Mark 16.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeSubheadings?: boolean

    /**
     * Show links above the text to the previous, current (if not showing the whole chapter) and next chapters in the Bible. You can modify the link by changing the link-url parameter.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeSurroundingChapters?: boolean

    /**
     * Same as the include-surrounding-chapters parameter above, but the links are rendered below the text. This value may also be the string smart, in which case the links will be shown based on the include-surrounding-chapters parameter.
     * @type {'true' | 'false' | 'smart'}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeSurroundingChaptersBelow?: V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum

    /**
     * Where embedded links to other passages should point. Applies only when include-surrounding-chapters is set to true.
     * @type {string}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly linkUrl?: string

    /**
     * Where embedded cross reference links should point. Only applies if include-crossrefs is true.
     * @type {string}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly crossrefUrl?: string

    /**
     * Where embedded links to the preface should point. Only applies if include-footnotes is true.
     * @type {string}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly prefaceUrl?: string

    /**
     * Include a link to the audio version of the requested passage. The link appears in a small tag in the passage\&#39;s identifying h2 tag.
     * @type {boolean}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly includeAudioLink?: boolean

    /**
     * Which feature to attach the audio link to. Must be either passage or heading.
     * @type {'passage' | 'heading'}
     * @memberof DefaultApiV3PassageHtmlGet
     */
    readonly attachAudioLinkTo?: V3PassageHtmlGetAttachAudioLinkToEnum
}

/**
 * Request parameters for v3PassageSearchGet operation in DefaultApi.
 * @export
 * @interface DefaultApiV3PassageSearchGetRequest
 */
export interface DefaultApiV3PassageSearchGetRequest {
    /**
     * The search query. If you want results for an exact phrase, wrap your query in double quotes. For instance, the query in love returns many more results than the query \&quot;in love\&quot; because the latter only returns matches for the exact phrase.
     * @type {string}
     * @memberof DefaultApiV3PassageSearchGet
     */
    readonly q: string

    /**
     * The number of results per page.
     * @type {number}
     * @memberof DefaultApiV3PassageSearchGet
     */
    readonly pageSize?: number

    /**
     * Which page of results you want. This parameter works in conjunction with the page-size parameter.
     * @type {number}
     * @memberof DefaultApiV3PassageSearchGet
     */
    readonly page?: number
}

/**
 * Request parameters for v3PassageTextGet operation in DefaultApi.
 * @export
 * @interface DefaultApiV3PassageTextGetRequest
 */
export interface DefaultApiV3PassageTextGetRequest {
    /**
     * This is the requested passage. We try our best to parse a meaningful passage reference from this value.
     * @type {string}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly q: string

    /**
     * Include the passage reference before the text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includePassageReferences?: boolean

    /**
     * Include verse numbers.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeVerseNumbers?: boolean

    /**
     * Include the verse number for the first verse of a chapter.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeFirstVerseNumbers?: boolean

    /**
     * Include callouts to footnotes in the text.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeFootnotes?: boolean

    /**
     * Include footnote bodies below the text. Only works if include-footnotes is also true.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeFootnoteBody?: boolean

    /**
     * Include section headings. For example, the section heading of Matthew 5 is \&quot;The Sermon on the Mount\&quot;.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeHeadings?: boolean

    /**
     * Include \&quot;(ESV)\&quot; at the end of the text. Mutually exclusive with include-copyright. This fulfills your copyright display requirements.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeShortCopyright?: boolean

    /**
     * Include a copyright notice at the end of the text. Mutually exclusive with include-short-copyright. This fulfills your copyright display requirements.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeCopyright?: boolean

    /**
     * Include a line of equal signs (&#x3D;&#x3D;&#x3D;&#x3D;) above the beginning of each passage.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includePassageHorizontalLines?: boolean

    /**
     * Include a visual line of underscores (____) above each section heading.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeHeadingHorizontalLines?: boolean

    /**
     * Controls the length of the line for include-passage-horizontal-lines and include-heading-horizontal-lines.
     * @type {number}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly horiztonalLineLength?: number

    /**
     * Include \&quot;Selah\&quot; in certain Psalms.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly includeSelahs?: boolean

    /**
     * Controls indentation.
     * @type {'space' | 'tab'}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly indentUsing?: V3PassageTextGetIndentUsingEnum

    /**
     * Controls how many indentation characters start a paragraph.
     * @type {number}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly indentParagraphs?: number

    /**
     * Controls indentation of poetry lines.
     * @type {boolean}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly indentPoetry?: boolean

    /**
     * Controls how many indentation characters are used per indentation level for poetry lines.
     * @type {number}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly indentPoetryLines?: number

    /**
     * Controls how many indentation characters are used for \&quot;Declares the LORD\&quot; in some of the prophets.\&quot;
     * @type {number}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly indentDeclares?: number

    /**
     * Controls how many indentation characters are used for Psalm doxologies.
     * @type {number}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly indentPsalmDoxology?: number

    /**
     * Controls how long a line can be before it is wrapped. Use 0 for unlimited line lengths.
     * @type {number}
     * @memberof DefaultApiV3PassageTextGet
     */
    readonly lineLength?: number
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get Passage Audio
     * @param {DefaultApiV3PassageAudioGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v3PassageAudioGet(requestParameters: DefaultApiV3PassageAudioGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v3PassageAudioGet(requestParameters.q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Passage HTML
     * @param {DefaultApiV3PassageHtmlGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v3PassageHtmlGet(requestParameters: DefaultApiV3PassageHtmlGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v3PassageHtmlGet(requestParameters.q, requestParameters.includePassageReferences, requestParameters.includeVerseNumbers, requestParameters.includeFirstVerseNumbers, requestParameters.includeFootnotes, requestParameters.includeFootnoteBody, requestParameters.includeHeadings, requestParameters.includeShortCopyright, requestParameters.includeCopyright, requestParameters.includeCssLink, requestParameters.inlineStyles, requestParameters.wrappingDiv, requestParameters.divClasses, requestParameters.paragraphTag, requestParameters.includeBookTitles, requestParameters.includeVerseAnchors, requestParameters.includeChapterNumbers, requestParameters.includeCrossrefs, requestParameters.includeSubheadings, requestParameters.includeSurroundingChapters, requestParameters.includeSurroundingChaptersBelow, requestParameters.linkUrl, requestParameters.crossrefUrl, requestParameters.prefaceUrl, requestParameters.includeAudioLink, requestParameters.attachAudioLinkTo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search for Passages
     * @param {DefaultApiV3PassageSearchGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v3PassageSearchGet(requestParameters: DefaultApiV3PassageSearchGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v3PassageSearchGet(requestParameters.q, requestParameters.pageSize, requestParameters.page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Passage Text
     * @param {DefaultApiV3PassageTextGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public v3PassageTextGet(requestParameters: DefaultApiV3PassageTextGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).v3PassageTextGet(requestParameters.q, requestParameters.includePassageReferences, requestParameters.includeVerseNumbers, requestParameters.includeFirstVerseNumbers, requestParameters.includeFootnotes, requestParameters.includeFootnoteBody, requestParameters.includeHeadings, requestParameters.includeShortCopyright, requestParameters.includeCopyright, requestParameters.includePassageHorizontalLines, requestParameters.includeHeadingHorizontalLines, requestParameters.horiztonalLineLength, requestParameters.includeSelahs, requestParameters.indentUsing, requestParameters.indentParagraphs, requestParameters.indentPoetry, requestParameters.indentPoetryLines, requestParameters.indentDeclares, requestParameters.indentPsalmDoxology, requestParameters.lineLength, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum = {
    True: 'true',
    False: 'false',
    Smart: 'smart'
} as const;
export type V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum = typeof V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum[keyof typeof V3PassageHtmlGetIncludeSurroundingChaptersBelowEnum];
/**
 * @export
 */
export const V3PassageHtmlGetAttachAudioLinkToEnum = {
    Passage: 'passage',
    Heading: 'heading'
} as const;
export type V3PassageHtmlGetAttachAudioLinkToEnum = typeof V3PassageHtmlGetAttachAudioLinkToEnum[keyof typeof V3PassageHtmlGetAttachAudioLinkToEnum];
/**
 * @export
 */
export const V3PassageTextGetIndentUsingEnum = {
    Space: 'space',
    Tab: 'tab'
} as const;
export type V3PassageTextGetIndentUsingEnum = typeof V3PassageTextGetIndentUsingEnum[keyof typeof V3PassageTextGetIndentUsingEnum];


